---
title: Stackbit Azimuth Theme
baseURL: "/"
params:
  palette: blue
  header:
    title: Azimuth
    logo_img: images/logo.png
    has_nav: true
  footer:
    logo_img: images/logo_alt.png
    tagline: SaaS theme by Stackbit
    has_nav: true
    nav_title: Company
    has_social: true
    social_title: Community
    content: "&copy; Ami Agro Agency. All rights reserved."
    links:
    - text: Made with Ami Agro Agency
      url: http://www.amiagrogroup.com
      new_window: true
disableKinds:
- RSS
