---
label: products
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: field_group_list
  name: sections
  label: sections
  fields:
  - type: text
    name: section_id
    label: section_id
  - type: text
    name: component
    label: component
  - type: text
    name: type
    label: type
  - type: file
    name: image
    label: image
  - type: text
    name: title
    label: title
  - type: text
    name: content
    label: content
  - type: field_group_list
    name: actions
    label: actions
    fields:
    - type: text
      name: label
      label: label
    - type: text
      name: url
      label: url
- type: text
  name: layout
  label: layout
